[ 2025-07-06 14:54:37,586 ] - 68 - INFO - Started data ingestion
[ 2025-07-06 15:02:08,104 ] - 36 - INFO - error occured in python script [D:\Network Security\networksecurity\components\dataingestion.py] line number [31] error message ['Index' object is not callable]
[ 2025-07-06 15:02:08,104 ] - 76 - INFO - error occured in python script [D:\Network Security\networksecurity\components\dataingestion.py] line number [69] error message [error occured in python script [D:\Network Security\networksecurity\components\dataingestion.py] line number [31] error message ['Index' object is not callable]]
[ 2025-07-06 15:02:08,104 ] - 16 - INFO - error occured in python script [D:\Network Security\main.py] line number [13] error message [error occured in python script [D:\Network Security\networksecurity\components\dataingestion.py] line number [69] error message [error occured in python script [D:\Network Security\networksecurity\components\dataingestion.py] line number [31] error message ['Index' object is not callable]]]
