[ 2025-07-18 20:22:06,211 ] - 52 - INFO - Starting the training pipeline.
[ 2025-07-18 20:22:06,211 ] - 20 - INFO - Start data ingestion
[ 2025-07-18 20:22:06,211 ] - 74 - INFO - Started data ingestion
[ 2025-07-18 20:22:13,540 ] - 52 - INFO - Spliiting the data as train and test set started
[ 2025-07-18 20:22:13,559 ] - 54 - INFO - Spliiting the data as train and test set ended
[ 2025-07-18 20:22:13,559 ] - 62 - INFO - Exporting train and test file path
[ 2025-07-18 20:22:13,757 ] - 65 - INFO - Exported train and test file path
[ 2025-07-18 20:22:13,757 ] - 23 - INFO - Data ingestion completed.
[ 2025-07-18 20:22:13,757 ] - 24 - INFO - Data ingestion artifacts Data_Ingestion_Artifact(trained_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\test.csv')
[ 2025-07-18 20:22:13,765 ] - 33 - INFO - Data validation started
[ 2025-07-18 20:22:13,958 ] - 33 - INFO - Expected columns: 31, Found: 31
[ 2025-07-18 20:22:13,958 ] - 33 - INFO - Expected columns: 31, Found: 31
[ 2025-07-18 20:22:14,391 ] - 36 - INFO - Data validation completed
[ 2025-07-18 20:22:14,391 ] - 37 - INFO - Data validation artifacts Data_Ingestion_Artifact(trained_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\test.csv')
[ 2025-07-18 20:22:14,391 ] - 46 - INFO - Data transformation started
[ 2025-07-18 20:22:14,391 ] - 45 - INFO - Started the data transformation
[ 2025-07-18 20:22:14,522 ] - 49 - INFO - Separating input and output features
[ 2025-07-18 20:22:14,523 ] - 32 - INFO - Entered the get_data_transformer_object function
[ 2025-07-18 20:22:14,557 ] - 62 - INFO - Transformation on train and test input features done.
[ 2025-07-18 20:22:14,557 ] - 66 - INFO - Saving array and preprocessor object
[ 2025-07-18 20:22:14,557 ] - 78 - INFO - error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']
[ 2025-07-18 20:22:14,557 ] - 53 - INFO - error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]
[ 2025-07-18 20:22:14,557 ] - 74 - INFO - error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [70] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]]
[ 2025-07-18 20:22:14,557 ] - 58 - ERROR - error occured in python script [D:\Network Security\app.py] line number [54] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [70] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]]]
[ 2025-07-18 20:22:17,561 ] - 52 - INFO - Starting the training pipeline.
[ 2025-07-18 20:22:17,561 ] - 20 - INFO - Start data ingestion
[ 2025-07-18 20:22:17,561 ] - 74 - INFO - Started data ingestion
[ 2025-07-18 20:22:26,471 ] - 52 - INFO - Spliiting the data as train and test set started
[ 2025-07-18 20:22:26,471 ] - 54 - INFO - Spliiting the data as train and test set ended
[ 2025-07-18 20:22:26,471 ] - 62 - INFO - Exporting train and test file path
[ 2025-07-18 20:22:26,627 ] - 65 - INFO - Exported train and test file path
[ 2025-07-18 20:22:26,643 ] - 23 - INFO - Data ingestion completed.
[ 2025-07-18 20:22:26,643 ] - 24 - INFO - Data ingestion artifacts Data_Ingestion_Artifact(trained_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\test.csv')
[ 2025-07-18 20:22:26,643 ] - 33 - INFO - Data validation started
[ 2025-07-18 20:22:26,768 ] - 33 - INFO - Expected columns: 31, Found: 31
[ 2025-07-18 20:22:26,768 ] - 33 - INFO - Expected columns: 31, Found: 31
[ 2025-07-18 20:22:27,130 ] - 36 - INFO - Data validation completed
[ 2025-07-18 20:22:27,130 ] - 37 - INFO - Data validation artifacts Data_Ingestion_Artifact(trained_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\07_18_2025_20_20_10\\data_ingestion\\ingested\\test.csv')
[ 2025-07-18 20:22:27,130 ] - 46 - INFO - Data transformation started
[ 2025-07-18 20:22:27,130 ] - 45 - INFO - Started the data transformation
[ 2025-07-18 20:22:27,255 ] - 49 - INFO - Separating input and output features
[ 2025-07-18 20:22:27,255 ] - 32 - INFO - Entered the get_data_transformer_object function
[ 2025-07-18 20:22:27,270 ] - 62 - INFO - Transformation on train and test input features done.
[ 2025-07-18 20:22:27,270 ] - 66 - INFO - Saving array and preprocessor object
[ 2025-07-18 20:22:27,270 ] - 78 - INFO - error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']
[ 2025-07-18 20:22:27,270 ] - 53 - INFO - error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]
[ 2025-07-18 20:22:27,286 ] - 74 - INFO - error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [70] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]]
[ 2025-07-18 20:22:27,286 ] - 58 - ERROR - error occured in python script [D:\Network Security\app.py] line number [54] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [70] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]]]
