[ 2025-07-18 20:18:33,805 ] - 52 - INFO - Starting the training pipeline.
[ 2025-07-18 20:18:33,805 ] - 20 - INFO - Start data ingestion
[ 2025-07-18 20:18:33,805 ] - 74 - INFO - Started data ingestion
[ 2025-07-18 20:18:42,099 ] - 52 - INFO - Spliiting the data as train and test set started
[ 2025-07-18 20:18:42,115 ] - 54 - INFO - Spliiting the data as train and test set ended
[ 2025-07-18 20:18:42,115 ] - 62 - INFO - Exporting train and test file path
[ 2025-07-18 20:18:42,288 ] - 65 - INFO - Exported train and test file path
[ 2025-07-18 20:18:42,303 ] - 23 - INFO - Data ingestion completed.
[ 2025-07-18 20:18:42,303 ] - 24 - INFO - Data ingestion artifacts Data_Ingestion_Artifact(trained_file_path='Artifacts\\07_18_2025_20_18_16\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\07_18_2025_20_18_16\\data_ingestion\\ingested\\test.csv')
[ 2025-07-18 20:18:42,303 ] - 33 - INFO - Data validation started
[ 2025-07-18 20:18:42,573 ] - 33 - INFO - Expected columns: 31, Found: 31
[ 2025-07-18 20:18:42,573 ] - 33 - INFO - Expected columns: 31, Found: 31
[ 2025-07-18 20:18:43,069 ] - 36 - INFO - Data validation completed
[ 2025-07-18 20:18:43,069 ] - 37 - INFO - Data validation artifacts Data_Ingestion_Artifact(trained_file_path='Artifacts\\07_18_2025_20_18_16\\data_ingestion\\ingested\\train.csv', test_file_path='Artifacts\\07_18_2025_20_18_16\\data_ingestion\\ingested\\test.csv')
[ 2025-07-18 20:18:43,069 ] - 46 - INFO - Data transformation started
[ 2025-07-18 20:18:43,069 ] - 45 - INFO - Started the data transformation
[ 2025-07-18 20:18:43,293 ] - 49 - INFO - Separating input and output features
[ 2025-07-18 20:18:43,305 ] - 32 - INFO - Entered the get_data_transformer_object function
[ 2025-07-18 20:18:43,324 ] - 62 - INFO - Transformation on train and test input features done.
[ 2025-07-18 20:18:43,325 ] - 66 - INFO - Saving array and preprocessor object
[ 2025-07-18 20:18:43,326 ] - 78 - INFO - error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']
[ 2025-07-18 20:18:43,326 ] - 53 - INFO - error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]
[ 2025-07-18 20:18:43,326 ] - 74 - INFO - error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [70] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]]
[ 2025-07-18 20:18:43,326 ] - 58 - ERROR - error occured in python script [D:\Network Security\app.py] line number [54] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [70] error message [error occured in python script [D:\Network Security\networksecurity\pipeline\training_pipeline.py] line number [48] error message [error occured in python script [D:\Network Security\networksecurity\components\datatransformation.py] line number [67] error message ['DataIngestionConfig' object has no attribute 'train_data_transformed_dir']]]]
